-- VDAN Template — import WISO members incl. Jugendkarte flag
-- Source: Aktuelle Mitglieder.xlsx (export date: 2026-02-20)
-- Run this after: 12_cto_qr_hidden_and_member_no.sql

begin;

create table if not exists public.club_members (
  member_no text primary key,
  first_name text,
  last_name text,
  status text,
  membership_kind text,
  fishing_card_type text,
  is_youth boolean not null default false,
  role text not null default 'member' check (role in ('member','vorstand','admin')),
  wiso_roles text,
  updated_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create index if not exists idx_club_members_is_youth on public.club_members(is_youth);
create index if not exists idx_club_members_status on public.club_members(status);

insert into public.club_members (
  member_no, first_name, last_name, status, membership_kind, fishing_card_type, is_youth, role, wiso_roles
)
values
('712', 'Justin', 'Lang', 'Aktiv', 'Mitglied', 'Rheinlos Erwachsener', false, 'member', null),
('711', 'Rüdiger', 'Kopf', 'Aktiv', 'Mitglied', 'Rheinlos Erwachsener', false, 'member', 'Mitglied'),
('710', 'Hubert', 'Stein', 'Aktiv', 'Mitglied', 'Innenwasser + Rheinlos', false, 'member', 'Mitglied'),
('709', 'Thomas', 'Wanzke', 'Aktiv', 'Mitglied', 'Innenwasser + Rheinlos', false, 'member', 'Mitglied'),
('708', 'Emil', 'Binder', 'Aktiv', 'Jugend', 'Innenwasser + Rheinlos Jugend', true, 'member', null),
('707', 'Moritz', 'Heimburger', 'Aktiv', 'Jugend', 'Innenwasser + Rheinlos Jugend', true, 'member', null),
('706', 'Gabriel', 'Imbeault', 'Aktiv', 'Jugend', 'Innenwasser + Rheinlos Jugend', true, 'member', null),
('705', 'Valentin', 'Gemidji', 'Aktiv', 'Jugend', 'Innenwasser + Rheinlos Jugend', true, 'member', null),
('704', 'Micka', 'Hellmuth', 'Aktiv', 'Jugend', 'Innenwasser + Rheinlos Jugend', true, 'member', null),
('703', 'Nico', 'Fritsch', 'Aktiv', 'Mitglied', 'Innenwasser + Rheinlos', false, 'member', null),
('702', '-', 'VDAN Admin', 'Passiv', '-', '-', false, 'member', 'Administrator'),
('701', 'Raphael', 'Gutowski', 'Aktiv', 'Mitglied', 'Innenwasser + Rheinlos', false, 'member', 'Mitglied'),
('700', 'Hannes', 'Heitz', 'Aktiv', 'Mitglied', 'Innenwasser + Rheinlos', false, 'member', null),
('699', 'Raul', 'Lorenzi', 'Aktiv', 'Jugend', 'Innenwasser + Rheinlos Jugend', true, 'member', null),
('698', 'Jens', 'Lederle', 'Aktiv', 'Mitglied', 'Innenwasser + Rheinlos', false, 'member', null),
('697', 'Silas', 'Jochheim', 'Aktiv', 'Mitglied', 'Rheinlos Erwachsener', false, 'member', null),
('696', 'Sven', 'Weidt', 'Aktiv', 'Mitglied', 'Rheinlos Erwachsener', false, 'member', null),
('694', 'Oliver', 'Ziegler', 'Aktiv', 'Mitglied', 'Innenwasser + Rheinlos', false, 'member', null),
('693', 'Hannes Rolf', 'Oschwald', 'Aktiv', 'Jugend', 'Innenwasser + Rheinlos Jugend', true, 'member', null),
('692', 'Steven', 'Binder', 'Aktiv', 'Mitglied', 'Rheinlos Erwachsener', false, 'member', null),
('691', 'Meo', 'Schönleber', 'Aktiv', 'Jugend', 'Innenwasser + Rheinlos Jugend', true, 'member', null),
('690', 'Mike', 'Wagner', 'Aktiv', 'Mitglied', 'Rheinlos Erwachsener', false, 'member', null),
('689', 'Luis', 'Henke', 'Aktiv', 'Jugend', 'Innenwasser + Rheinlos Jugend', true, 'member', null),
('688', 'Ferdinand', 'Binder', 'Aktiv', 'Jugend', 'Innenwasser + Rheinlos Jugend', true, 'member', null),
('687', 'Björn', 'Breithaupt', 'Aktiv', 'Mitglied', 'Innenwasser + Rheinlos', false, 'member', null),
('686', 'Christian', 'Mück', 'Aktiv', 'Mitglied', 'Innenwasser + Rheinlos', false, 'member', null),
('685', 'Eric', 'Reichel', 'Aktiv', 'Mitglied', 'Rheinlos Erwachsener', false, 'member', null),
('684', 'Tom', 'Klemt', 'Aktiv', 'Mitglied', 'Innenwasser + Rheinlos', false, 'member', null),
('683', 'Marin', 'Beck', 'Aktiv', 'Jugend', 'Innenwasser + Rheinlos Jugend', true, 'member', null),
('682', 'Tristan', 'Beck', 'Aktiv', 'Jugend', 'Innenwasser + Rheinlos Jugend', true, 'member', null),
('681', 'Timo', 'Schandelmeyer', 'Aktiv', 'Mitglied', 'Rheinlos Erwachsener', false, 'member', null),
('680', 'Lui', 'Leuthner', 'Aktiv', 'Jugend', 'Innenwasser + Rheinlos Jugend', true, 'member', null),
('679', 'Felix', 'Beathalter', 'Aktiv', 'Jugend', 'Innenwasser + Rheinlos Jugend', true, 'member', null),
('677', 'Philipp', 'Sparwasser', 'Aktiv', 'Mitglied', 'Rheinlos Erwachsener', false, 'member', null),
('676', 'Michael', 'Roth', 'Aktiv', 'Mitglied', 'Innenwasser + Rheinlos', false, 'member', null),
('675', 'Sebastian', 'Heim', 'Aktiv', 'Mitglied', 'Innenwasser + Rheinlos', false, 'member', null),
('674', 'Sergej', 'Herr', 'Aktiv', 'Mitglied', 'Rheinlos Erwachsener', false, 'member', null),
('673', 'Stefan', 'Stulz', 'Aktiv', 'Mitglied', 'Innenwasser + Rheinlos', false, 'member', null),
('672', 'Andre', 'Glatz', 'Aktiv', 'Mitglied', 'Innenwasser + Rheinlos', false, 'member', null),
('671', 'Constantin', 'Grabner', 'Aktiv', 'Mitglied', 'Rheinlos Erwachsener', false, 'member', null),
('670', 'Pia', 'Ritter', 'Aktiv', 'Mitglied', 'Rheinlos Erwachsener', false, 'member', null),
('669', 'Dirk', 'Oschwald', 'Aktiv', 'Mitglied', 'Innenwasser + Rheinlos', false, 'member', null),
('668', 'Tim', 'Wieber', 'Aktiv', 'Jugend', 'Innenwasser + Rheinlos Jugend', true, 'member', null),
('667', 'Albert', 'Binder', 'Aktiv', 'Jugend', 'Innenwasser + Rheinlos Jugend', true, 'member', null),
('666', 'Henri', 'Euler', 'Aktiv', 'Jugend', 'Innenwasser + Rheinlos Jugend', true, 'member', null),
('665', 'Jonathan', 'Gröning', 'Aktiv', 'Jugend', 'Innenwasser + Rheinlos Jugend', true, 'member', null),
('664', 'Noah', 'Reitter', 'Aktiv', 'Jugend', 'Innenwasser + Rheinlos Jugend', true, 'member', null),
('663', 'Moritz', 'Oschwald', 'Aktiv', 'Jugend', 'Innenwasser + Rheinlos Jugend', true, 'member', null),
('662', 'Boris', 'Gröning', 'Aktiv', 'Mitglied', 'Innenwasser + Rheinlos', false, 'member', null),
('661', 'Janne', 'Grottendorfer', 'Aktiv', 'Jugend', 'Innenwasser + Rheinlos Jugend', true, 'member', null),
('660', 'Mats', 'Mild', 'Aktiv', 'Jugend', 'Innenwasser + Rheinlos Jugend', true, 'member', null),
('659', 'Sören', 'Mild', 'Aktiv', 'Jugend', 'Innenwasser + Rheinlos Jugend', true, 'member', null),
('658', 'Alexander', 'Diehl', 'Aktiv', 'Mitglied', 'Innenwasser Erwachsener', false, 'member', null),
('657', 'Hannes', 'Wess', 'Aktiv', 'Jugend', 'Innenwasser + Rheinlos Jugend', true, 'member', null),
('656', 'Elias', 'Lengle', 'Aktiv', 'Jugend', 'Innenwasser + Rheinlos', true, 'member', null),
('654', 'Michael', 'Hellmuth', 'Aktiv', 'Mitglied', 'Innenwasser + Rheinlos', false, 'member', null),
('653', 'Gabriel', 'Kaufmann', 'Aktiv', 'Mitglied', 'Rheinlos Erwachsener', false, 'member', null),
('652', 'Adrian', 'Thoma', 'Aktiv', 'Jugend', 'Innenwasser + Rheinlos Jugend', true, 'member', null),
('650', 'Mick', 'Leuthner', 'Aktiv', 'Jugend', 'Innenwasser + Rheinlos Jugend', true, 'member', null),
('649', 'Marc Robin', 'Karkossa', 'Passiv', 'Mitglied', '-', false, 'member', null),
('648', 'Juri', 'Gemidji', 'Aktiv', 'Mitglied', 'Innenwasser + Rheinlos', false, 'member', null),
('647', 'Till', 'Manthey', 'Aktiv', 'Mitglied', 'Innenwasser + Rheinlos', false, 'member', null),
('646', 'Jan-Kevin', 'Merz', 'Aktiv', 'Mitglied', 'Innenwasser + Rheinlos', false, 'member', null),
('645', 'Christian', 'Riedel', 'Aktiv', 'Mitglied', 'Innenwasser + Rheinlos', false, 'member', null),
('642', 'Gloria', 'Ritter', 'Aktiv', 'Mitglied', 'Innenwasser + Rheinlos', false, 'member', null),
('641', 'Michael', 'Wickert', 'Aktiv', 'Mitglied', 'Rheinlos Erwachsener', false, 'member', null),
('638', 'Matthias', 'Ehret', 'Aktiv', 'Mitglied', 'Innenwasser + Rheinlos', false, 'member', null),
('637', 'Ronja', 'Ritter', 'Aktiv', 'Jugend', 'Innenwasser + Rheinlos Jugend', true, 'member', null),
('636', 'Marco', 'Lanzillotti', 'Aktiv', 'Mitglied', 'Innenwasser + Rheinlos', false, 'member', null),
('635', 'Ramona', 'Lanzillotti', 'Aktiv', 'Vorstand', 'Innenwasser + Rheinlos VSS Btr. Bf', false, 'member', 'Finanzverwalter'),
('634', 'Yvonne', 'Ams', 'Aktiv', 'Mitglied', 'Innenwasser + Rheinlos', false, 'member', null),
('633', 'Francisco', 'Ceballos', 'Aktiv', 'Mitglied', 'Innenwasser + Rheinlos', false, 'member', null),
('629', 'Tobias Alexander', 'Rost', 'Aktiv', 'Mitglied', 'Rheinlos Erwachsener', false, 'member', null),
('627', 'Ben', 'Leuthner', 'Aktiv', 'Jugend', 'Innenwasser + Rheinlos Jugend', true, 'member', null),
('626', 'Daniel', 'Pigler', 'Aktiv', 'Mitglied', 'Innenwasser + Rheinlos', false, 'member', null),
('625', 'Mathias', 'Ficks', 'Passiv', 'Mitglied', '-', false, 'member', null),
('624', 'Elias', 'Kurz', 'Aktiv', 'Vorstand', 'Innenwasser + Rheinlos VSS Btr. Bf', false, 'member', 'Jugendleiter'),
('623', 'Joschua', 'Kurz', 'Aktiv', 'Mitglied', 'Innenwasser + Rheinlos', false, 'member', null),
('622', 'Patrick', 'Utz', 'Aktiv', 'Mitglied', 'Innenwasser + Rheinlos', false, 'member', null),
('621', 'Peter', 'Schneppenhorst', 'Aktiv', 'Mitglied', 'Rheinlos Erwachsener', false, 'member', null),
('620', 'Jeremie', 'Isele', 'Aktiv', 'Mitglied', 'Innenwasser + Rheinlos', false, 'member', null),
('619', 'Sascha', 'Maier', 'Aktiv', 'Mitglied', 'Rheinlos Erwachsener', false, 'member', null),
('618', 'Markus', 'Henke', 'Aktiv', 'Mitglied', 'Innenwasser + Rheinlos', false, 'member', null),
('617', 'Luka', 'Lederle', 'Aktiv', 'Vorstand', 'Innenwasser + Rheinlos VSS Btr. Bf', false, 'member', 'Jugendleiter'),
('616', 'Patrick', 'Beck', 'Aktiv', 'Mitglied', 'Innenwasser + Rheinlos', false, 'member', null),
('612', 'Alexander', 'Subat', 'Aktiv', 'Mitglied', 'Rheinlos Erwachsener', false, 'member', null),
('611', 'Martina', 'Migneault', 'Aktiv', 'Mitglied', 'Innenwasser + Rheinlos', false, 'member', null),
('609', 'Stefan', 'Joos', 'Aktiv', 'Mitglied', 'Innenwasser + Rheinlos', false, 'member', null),
('608', 'Jörg', 'Bonk', 'Aktiv', 'Mitglied', 'Innenwasser + Rheinlos', false, 'member', null),
('607', 'Volker', 'Kurz', 'Aktiv', 'Mitglied', 'Innenwasser + Rheinlos', false, 'member', null),
('606', 'Luca', 'Geiger', 'Aktiv', 'Jugend', 'Innenwasser + Rheinlos', true, 'member', null),
('605', 'Oskar', 'Weide', 'Aktiv', 'Mitglied', 'Innenwasser + Rheinlos', false, 'member', null),
('603', 'Tommy', 'Ritter', 'Aktiv', 'Mitglied', 'Innenwasser + Rheinlos', false, 'member', null),
('602', 'Volker', 'Ziegler', 'Aktiv', 'Mitglied', 'Innenwasser + Rheinlos Btr. bf', false, 'member', null),
('601', 'Daniel', 'Beckstett', 'Passiv', 'Mitglied', '-', false, 'member', null),
('599', 'Leon-Luca', 'Lauenroth', 'Passiv', '-', '-', false, 'member', null),
('598', 'Michael', 'Lauenroth', 'Aktiv', 'Mitglied', 'Innenwasser + Rheinlos Btr. bf', false, 'member', 'Administrator'),
('597', 'Louis', 'Mild', 'Passiv', 'Mitglied', '-', false, 'member', null),
('596', 'Tamara', 'Mild', 'Passiv', 'Mitglied', '-', false, 'member', null),
('595', 'Jamie', 'Leuthner', 'Aktiv', 'Mitglied', 'Innenwasser + Rheinlos', false, 'member', null),
('589', 'Esther', 'Fürle-Mauch', 'Passiv', 'Mitglied', '-', false, 'member', null),
('588', 'Noah', 'Mauch', 'Aktiv', 'Mitglied', 'Innenwasser + Rheinlos Btr. bf', false, 'member', null),
('587', 'Fabian', 'Horlacher', 'Aktiv', 'Mitglied', 'Innenwasser + Rheinlos', false, 'member', null),
('585', 'Stefan', 'Breithaupt', 'Passiv', 'Mitglied', '-', false, 'member', null),
('584', 'Monika', 'Reichmann', 'Passiv', 'Mitglied', '-', false, 'member', null),
('583', 'Paul Luis', 'Reichmann', 'Aktiv', 'Mitglied', 'Innenwasser + Rheinlos', false, 'member', null),
('581', 'Jannik', 'Haase', 'Passiv', 'Mitglied', '-', false, 'member', null),
('580', 'Gabriela', 'Benz', 'Aktiv', 'Mitglied', 'Innenwasser + Rheinlos', false, 'member', null),
('578', 'Markus', 'Helmcke Hryhoruk', 'Aktiv', 'Mitglied', 'Innenwasser Erwachsener', false, 'member', null),
('576', 'Sandra', 'Fischer', 'Aktiv', 'Mitglied', 'Innenwasser + Rheinlos', false, 'member', null),
('575', 'Bastian', 'Fischer', 'Aktiv', 'Mitglied', 'Rheinlos Erwachsener', false, 'member', null),
('570', 'Waldemar', 'Popp', 'Aktiv', 'Mitglied', 'Innenwasser + Rheinlos', false, 'member', null),
('569', 'Waldemar', 'Strecker', 'Aktiv', 'Mitglied', 'Rheinlos Erwachsener', false, 'member', null),
('568', 'Eugen', 'Strecker', 'Aktiv', 'Mitglied', 'Rheinlos Erwachsener', false, 'member', null),
('566', 'Michael', 'Moser', 'Passiv', 'Mitglied', '-', false, 'member', null),
('563', 'Heiko', 'Schwer', 'Aktiv', 'Mitglied', 'Innenwasser + Rheinlos', false, 'member', null),
('559', 'Johannes', 'Weiß', 'Passiv', 'Mitglied', '-', false, 'member', null),
('558', 'Christine', 'Weiß', 'Passiv', 'Mitglied', '-', false, 'member', null),
('557', 'Mathias', 'Leuthner', 'Aktiv', 'Mitglied', 'Innenwasser + Rheinlos', false, 'member', null),
('553', 'Jannis', 'Bühler', 'Aktiv', 'Mitglied', 'Innenwasser Erwachsener', false, 'member', null),
('547', 'Jannik', 'Wörner', 'Passiv', 'Mitglied', '-', false, 'member', null),
('546', 'Volker', 'Wörner', 'Passiv', 'Mitglied', '-', false, 'member', null),
('545', 'Marcel', 'Bühler', 'Aktiv', 'Mitglied', 'Innenwasser + Rheinlos', false, 'member', null),
('538', 'Martin', 'Schiff', 'Aktiv', 'Mitglied', 'Innenwasser + Rheinlos', false, 'member', null),
('537', 'Klaus', 'Ebert', 'Passiv', 'Mitglied', '-', false, 'member', null),
('536', 'Rolf', 'Bolz', 'Aktiv', 'Mitglied', 'Innenwasser + Rheinlos', false, 'member', null),
('535', 'Sebastian', 'Schandl', 'Aktiv', 'Mitglied', 'Innenwasser + Rheinlos', false, 'member', null),
('534', 'Gerald', 'Siefert', 'Aktiv', 'Mitglied', 'Innenwasser + Rheinlos', false, 'member', null),
('533', 'Lothar', 'Ritter', 'Aktiv', 'Mitglied', 'Innenwasser + Rheinlos', false, 'member', null),
('531', 'Axel', 'Kühweidner', 'Aktiv', 'Mitglied', 'Innenwasser Erwachsener', false, 'member', null),
('529', 'Jona', 'Schröder', 'Aktiv', 'Mitglied', 'Innenwasser + Rheinlos', false, 'member', null),
('528', 'Domenik', 'Kern', 'Passiv', 'Mitglied', '-', false, 'member', null),
('527', 'Fabian', 'Bruder', 'Aktiv', 'Mitglied', 'Rheinlos Erwachsener', false, 'member', null),
('525', 'Viktor', 'Kunau', 'Passiv', 'Mitglied', '-', false, 'member', null),
('524', 'Nico', 'Schmider', 'Aktiv', 'Mitglied', 'Innenwasser + Rheinlos', false, 'member', null),
('523', 'Andreas', 'Schmider', 'Passiv', 'Mitglied', '-', false, 'member', null),
('522', 'Daniela', 'Mild', 'Aktiv', 'Mitglied', 'Innenwasser Erwachsener', false, 'member', 'Mitglied'),
('521', 'Markus', 'Mild', 'Aktiv', 'Vorstand', 'Innenwasser + Rheinlos VSS Btr. Bf', false, 'member', 'Administrator'),
('520', 'Rainer', 'Mild', 'Aktiv', 'Mitglied', 'Innenwasser Erwachsener', false, 'member', null),
('519', 'Jean- Pierre', 'Leppert', 'Aktiv', 'Mitglied', 'Rheinlos Erwachsener', false, 'member', null),
('518', 'Frank', 'Schauber', 'Passiv', 'Mitglied', '-', false, 'member', null),
('517', 'Yannik', 'Matthis', 'Passiv', 'Mitglied', '-', false, 'member', null),
('516', 'Carola', 'Gänshirt', 'Passiv', 'Mitglied', '-', false, 'member', null),
('515', 'Dustin', 'Gänshirt', 'Passiv', 'Mitglied', '-', false, 'member', null),
('512', 'Horst', 'Preuschoff', 'Aktiv', 'Mitglied', 'Innenwasser + Rheinlos', false, 'member', null),
('511', 'Stefan', 'Bruder', 'Aktiv', 'Mitglied', 'Rheinlos Erwachsener', false, 'member', null),
('510', 'Felix', 'Däschle', 'Aktiv', 'Mitglied', 'Innenwasser + Rheinlos', false, 'member', null),
('508', 'Manuel', 'Kunz', 'Aktiv', 'Vorstand', 'Innenwasser + Rheinlos VSS Btr. Bf', false, 'member', 'Jugendleiter'),
('507', 'Michael', 'Kunz', 'Passiv', 'Mitglied', '-', false, 'member', null),
('505', 'Oliver', 'Reiff', 'Aktiv', 'Vorstand', 'Innenwasser + Rheinlos VSS Btr. Bf', false, 'member', 'Jugendleiter'),
('504', 'Birgit', 'Metzger', 'Passiv', 'Mitglied', '-', false, 'member', null),
('503', 'Marc', 'Lechien', 'Aktiv', 'Mitglied', 'Innenwasser + Rheinlos', false, 'member', null),
('499', 'Edgar', 'Ziborius', 'Passiv', 'Mitglied', '-', false, 'member', null),
('495', 'Johanna', 'Haase', 'Aktiv', 'Mitglied', 'Innenwasser Btr. bf', false, 'member', null),
('493', 'Yannick', 'Schwend', 'Aktiv', 'Mitglied', 'Innenwasser + Rheinlos', false, 'member', null),
('492', 'Reinhard', 'Schwend', 'Aktiv', 'Mitglied', 'Rheinlos Erwachsener', false, 'member', null),
('491', 'Michael', 'Braun', 'Aktiv', 'Mitglied', 'Innenwasser + Rheinlos', false, 'member', null),
('490', 'Spyridon', 'Messerschmidt', 'Aktiv', 'Mitglied', 'Innenwasser + Rheinlos', false, 'member', null),
('486', 'Antonio', 'Farrujia', 'Passiv', 'Mitglied', '-', false, 'member', null),
('483', 'Marcel', 'Klähr', 'Aktiv', 'Mitglied', 'Innenwasser + Rheinlos', false, 'member', null),
('481', 'Michael', 'Schönleber', 'Aktiv', 'Vorstand', 'Innenwasser + Rheinlos VSS Btr. Bf', false, 'member', 'Verwalter'),
('476', 'Philipp', 'Lienhard', 'Passiv', 'Mitglied', '-', false, 'member', null),
('475', 'Carsten', 'Lach', 'Aktiv', 'Mitglied', 'Innenwasser Erwachsener', false, 'member', null),
('474', 'Andreas', 'Leser', 'Aktiv', 'Mitglied', 'Innenwasser + Rheinlos', false, 'member', null),
('470', 'Louis', 'Kiesele', 'Passiv', 'Mitglied', '-', false, 'member', null),
('465', 'Sandra', 'Hannebauer', 'Passiv', 'Mitglied', '-', false, 'member', null),
('460', 'Wladimir', 'Belsch', 'Passiv', 'Mitglied', '-', false, 'member', null),
('458', 'Tim', 'Langenbach', 'Aktiv', 'Mitglied', 'Innenwasser + Rheinlos', false, 'member', null),
('445', 'Frank', 'Hessemann', 'Passiv', 'Mitglied', '-', false, 'member', null),
('439', 'Lutz', 'Weide', 'Passiv', 'Mitglied', '-', false, 'member', null),
('438', 'Ferdinand', 'Weide', 'Aktiv', 'Vorstand', 'Innenwasser + Rheinlos VSS Btr. Bf', false, 'member', 'Verwalter'),
('437', 'Lars', 'Lehmann', 'Aktiv', 'Mitglied', 'Innenwasser Erwachsener', false, 'member', 'Schriftführer'),
('436', 'Kevin', 'Gießler', 'Passiv', 'Mitglied', '-', false, 'member', null),
('435', 'Carlos', 'Farrujia', 'Passiv', 'Mitglied', '-', false, 'member', null),
('432', 'Morris', 'Zipf', 'Aktiv', 'Mitglied', 'Innenwasser + Rheinlos', false, 'member', null),
('421', 'Nils', 'Kutsch', 'Aktiv', 'Mitglied', 'Innenwasser + Rheinlos', false, 'member', null),
('415', 'Jakob', 'Ohm', 'Passiv', 'Mitglied', '-', false, 'member', null),
('414', 'Eugen', 'Revin', 'Passiv', 'Mitglied', '-', false, 'member', null),
('413', 'Rudi', 'Philipp', 'Aktiv', 'Mitglied', 'Innenwasser Erwachsener', false, 'member', null),
('412', 'Karin', 'Bühler', 'Aktiv', 'Mitglied', 'Innenwasser + Rheinlos', false, 'member', null),
('411', 'Timo', 'Hegeholz', 'Passiv', 'Mitglied', '-', false, 'member', null),
('410', 'David', 'Heim', 'Aktiv', 'Vorstand', 'Innenwasser + Rheinlos VSS Btr. Bf', false, 'member', 'Verwalter'),
('408', 'Andrej', 'Elli', 'Passiv', 'Mitglied', '-', false, 'member', null),
('398', 'Wladimir', 'Grasmik', 'Aktiv', 'Mitglied', 'Innenwasser + Rheinlos', false, 'member', null),
('397', 'Alexander', 'Lomako', 'Passiv', 'Mitglied', '-', false, 'member', null),
('393', 'Andreas', 'Weber', 'Aktiv', 'Mitglied', 'Innenwasser + Rheinlos', false, 'member', null),
('392', 'Markus', 'Förster', 'Passiv', 'Mitglied', '-', false, 'member', null),
('390', 'Erwin', 'Abel', 'Passiv', 'Mitglied', '-', false, 'member', null),
('389', 'Johannes', 'Buchholz', 'Aktiv', 'Mitglied', 'Innenwasser + Rheinlos', false, 'member', null),
('387', 'Lukas', 'Bing', 'Aktiv', 'Mitglied', 'Innenwasser Erwachsener', false, 'member', null),
('384', 'Bernd', 'Thielecke', 'Passiv', '-', '-', false, 'member', null),
('381', 'Michael', 'Farrujia', 'Passiv', 'Mitglied', '-', false, 'member', null),
('374', 'Siegfried', 'Großholz', 'Passiv', 'Mitglied', '-', false, 'member', null),
('373', 'Alexander', 'Michel', 'Passiv', 'Mitglied', '-', false, 'member', null),
('372', 'Jakob', 'Michel', 'Aktiv', 'Mitglied', 'Innenwasser + Rheinlos', false, 'member', null),
('371', 'Ivan', 'Ossipov', 'Passiv', 'Mitglied', '-', false, 'member', null),
('370', 'Bastian', 'Hädicke', 'Aktiv', 'Mitglied', 'Innenwasser + Rheinlos', false, 'member', null),
('369', 'Philipp', 'Reckling', 'Aktiv', 'Mitglied', 'Rheinlos Erwachsener', false, 'member', null),
('363', 'Jakob', 'Weber', 'Aktiv', 'Mitglied', 'Rheinlos Erwachsener', false, 'member', null),
('362', 'Mathias', 'Jäckle', 'Passiv', 'Mitglied', '-', false, 'member', null),
('361', 'Wladimir', 'Koch', 'Aktiv', 'Mitglied', 'Innenwasser + Rheinlos', false, 'member', null),
('360', 'Ortwin', 'Grottendorfer', 'Aktiv', 'Mitglied', 'Innenwasser + Rheinlos', false, 'member', null),
('359', 'Jürgen', 'Grottendorfer', 'Aktiv', 'Mitglied', 'Innenwasser + Rheinlos', false, 'member', null),
('345', 'Karl-Hermann', 'Lauer', 'Aktiv', 'Mitglied', 'Innenwasser + Rheinlos Btr. bf', false, 'member', 'Mitglied'),
('340', 'Cornelius', 'Leser', 'Aktiv', 'Mitglied', 'Rheinlos Erwachsener', false, 'member', null),
('338', 'Nadine', 'Lauer', 'Passiv', 'Mitglied', '-', false, 'member', null),
('334', 'Johannes', 'Weide', 'Aktiv', 'Mitglied', 'Innenwasser + Rheinlos', false, 'member', null),
('332', 'Björn', 'Kern', 'Aktiv', 'Mitglied', 'Innenwasser + Rheinlos', false, 'member', null),
('330', 'Maik', 'Wieber', 'Passiv', 'Mitglied', '-', false, 'member', null),
('329', 'Gerd', 'Heimburger', 'Aktiv', 'Ehrenmitglied', 'Innewasser Ehrenmitglied + Rheinlos Erwachsener', false, 'member', null),
('328', 'Jörg', 'Dier', 'Aktiv', 'Mitglied', 'Innenwasser Erwachsener', false, 'member', null),
('327', 'Michael', 'Braun', 'Passiv', 'Mitglied', '-', false, 'member', null),
('326', 'Viktor', 'Rudi', 'Aktiv', 'Mitglied', 'Innenwasser + Rheinlos', false, 'member', null),
('323', 'Waldemar', 'Dillmann', 'Aktiv', 'Mitglied', 'Innenwasser + Rheinlos', false, 'member', null),
('322', 'Êrika', 'Langhans-Kappis', 'Passiv', 'Mitglied', '-', false, 'member', null),
('321', 'Achim', 'Kappis', 'Passiv', 'Mitglied', '-', false, 'member', null),
('319', 'Werner', 'Stiefel', 'Passiv', 'Mitglied', '-', false, 'member', null),
('318', 'Wilfried', 'Stern', 'Passiv', 'Ehrenmitglied', '-', false, 'member', null),
('317', 'Klaus', 'Stengg', 'Passiv', 'Mitglied', '-', false, 'member', null),
('316', 'Benjamin', 'Stengg', 'Passiv', 'Mitglied', '-', false, 'member', null),
('313', 'Michael', 'Stahl', 'Aktiv', 'Mitglied', 'Innenwasser + Rheinlos Btr. bf', false, 'member', null),
('308', 'Eberhard', 'Spothelfer', 'Passiv', 'Mitglied', '-', false, 'member', null),
('306', 'Hubert', 'Singler', 'Aktiv', 'Mitglied', 'Innenwasser + Rheinlos', false, 'member', null),
('304', 'Gregor', 'Sexauer', 'Aktiv', 'Mitglied', 'Innenwasser + Rheinlos', false, 'member', null),
('303', 'Patrick', 'Schwarz', 'Passiv', 'Mitglied', '-', false, 'member', null),
('302', 'Oswald', 'Schwarz', 'Aktiv', 'Ehrenmitglied', 'Innenwasser Ehrenmitglied', false, 'member', null),
('301', 'Rolf', 'Schuldis', 'Aktiv', 'Mitglied', 'Innenwasser + Rheinlos', false, 'member', null),
('300', 'Rolf', 'Schüssele', 'Passiv', 'Mitglied', '-', false, 'member', null),
('297', 'Karlheinz', 'Schönleber', 'Passiv', 'Mitglied', '-', false, 'member', null),
('293', 'Pascal', 'Schnak', 'Passiv', 'Mitglied', '-', false, 'member', null),
('292', 'Holger', 'Schnak', 'Aktiv', 'Mitglied', 'Innenwasser + Rheinlos', false, 'member', null),
('291', 'Harald', 'Schnak', 'Passiv', 'Mitglied', '-', false, 'member', null),
('290', 'Detleff', 'Schnak', 'Aktiv', 'Mitglied', 'Innenwasser + Rheinlos', false, 'member', null),
('289', 'Boris', 'Schnak', 'Passiv', 'Mitglied', '-', false, 'member', null),
('284', 'Mario', 'Schiff', 'Passiv', 'Mitglied', '-', false, 'member', null),
('280', 'Bernd', 'Sailer', 'Passiv', 'Mitglied', '-', false, 'member', null),
('279', 'Sylvia', 'Ruf', 'Passiv', 'Mitglied', '-', false, 'member', null),
('277', 'Rolf', 'Rosewich', 'Passiv', '-', '-', false, 'member', null),
('276', 'Harry', 'Ritter', 'Aktiv', 'Mitglied', 'Innenwasser + Rheinlos', false, 'member', null),
('274', 'Patrick', 'Ringwald', 'Aktiv', 'Mitglied', 'Innenwasser + Rheinlos', false, 'member', null),
('269', 'Bernhard', 'Ringwald', 'Aktiv', 'Ehrenmitglied', 'Innewasser Ehrenmitglied + Rheinlos Erwachsener', false, 'member', null),
('267', 'Maritta', 'Rieth', 'Passiv', 'Mitglied', '-', false, 'member', null),
('266', 'Klaus', 'Rieth', 'Aktiv', 'Ehrenmitglied', 'Innewasser Ehrenmitglied + Rheinlos Erwachsener', false, 'member', null),
('265', 'Christa', 'Rieth', 'Passiv', 'Mitglied', '-', false, 'member', null),
('261', 'Tobias', 'Reith', 'Aktiv', 'Mitglied', 'Innenwasser + Rheinlos', false, 'member', null),
('260', 'Heinz', 'Reith', 'Aktiv', 'Ehrenmitglied', 'Innewasser Ehrenmitglied + Rheinlos Erwachsener', false, 'member', null),
('251', 'Claus', 'Philipp', 'Aktiv', 'Mitglied', 'Innenwasser Erwachsener', false, 'member', null),
('249', 'Rainer', 'Ostermann', 'Passiv', 'Mitglied', '-', false, 'member', null),
('245', 'Simon', 'Oberle', 'Passiv', 'Mitglied', '-', false, 'member', null),
('243', 'Rolf', 'Oberle', 'Aktiv', 'Ehrenmitglied', 'Innewasser Ehrenmitglied + Rheinlos Erwachsener', false, 'member', null),
('242', 'Roland', 'Oberle', 'Aktiv', 'Mitglied', 'Innenwasser + Rheinlos', false, 'member', null),
('241', 'Michael', 'Oberle', 'Passiv', 'Mitglied', '-', false, 'member', null),
('239', 'Martin', 'Oberle', 'Passiv', 'Mitglied', '-', false, 'member', null),
('238', 'Kurt', 'Oberle', 'Passiv', 'Mitglied', '-', false, 'member', null),
('233', 'Dieter', 'Oberle', 'Aktiv', 'Ehrenmitglied', 'Innewasser Ehrenmitglied + Rheinlos Erwachsener', false, 'member', null),
('232', 'Daniel', 'Oberle', 'Aktiv', 'Mitglied', 'Innenwasser + Rheinlos', false, 'member', null),
('227', 'Siegfried', 'Munz', 'Passiv', 'Mitglied', '-', false, 'member', null),
('224', 'Benjamin', 'Mosbach', 'Passiv', 'Mitglied', '-', false, 'member', null),
('223', 'Steffen', 'Mittag', 'Passiv', 'Mitglied', '-', false, 'member', null),
('219', 'Jürgen', 'Metzger', 'Passiv', '-', '-', false, 'member', null),
('218', 'Horst', 'Metzger', 'Passiv', 'Mitglied', '-', false, 'member', null),
('213', 'Jürgen', 'Maurer', 'Passiv', 'Mitglied', '-', false, 'member', null),
('211', 'Günter', 'Matthis', 'Passiv', 'Mitglied', '-', false, 'member', null),
('209', 'Dirk', 'Ostermann', 'Passiv', 'Mitglied', '-', false, 'member', null),
('208', 'Hermann', 'Mast', 'Passiv', 'Mitglied', '-', false, 'member', null),
('203', 'Klaus', 'Löffler', 'Aktiv', 'Ehrenmitglied', 'Innenwasser Ehrenmitglied', false, 'member', null),
('201', 'Franz', 'Leutner', 'Passiv', 'Ehrenmitglied', '-', false, 'member', null),
('200', 'Stefan', 'Leuthner', 'Passiv', 'Mitglied', '-', false, 'member', null),
('199', 'Martin', 'Leuthner', 'Passiv', 'Mitglied', '-', false, 'member', null),
('198', 'Axel', 'Leuthner', 'Passiv', 'Mitglied', '-', false, 'member', null),
('194', 'Ulrich', 'Lehmann', 'Passiv', 'Mitglied', '-', false, 'member', null),
('191', 'Phillippe', 'Lechien', 'Passiv', 'Mitglied', '-', false, 'member', null),
('186', 'Michael', 'Langenbach', 'Aktiv', 'Mitglied', 'Innenwasser + Rheinlos', false, 'member', null),
('184', 'Florian', 'Langenbach', 'Passiv', 'Mitglied', '-', false, 'member', null),
('181', 'Karlheinz', 'Kutsch', 'Aktiv', 'Mitglied', 'Innenwasser + Rheinlos', false, 'member', null),
('177', 'Wolfgang', 'Knauber', 'Aktiv', 'Mitglied', 'Innenwasser + Rheinlos', false, 'member', null),
('175', 'Peter', 'Klotz', 'Passiv', 'Mitglied', '-', false, 'member', null),
('169', 'Arne', 'Kilgus', 'Aktiv', 'Mitglied', 'Innenwasser + Rheinlos', false, 'member', null),
('165', 'Markus', 'Kern', 'Aktiv', 'Mitglied', 'Innenwasser + Rheinlos', false, 'member', null),
('164', 'Günther', 'Kern', 'Aktiv', 'Ehrenmitglied', 'Innewasser Ehrenmitglied + Rheinlos Erwachsener', false, 'member', null),
('159', 'Rudolf', 'Jundt', 'Passiv', 'Mitglied', '-', false, 'member', null),
('158', 'Ines', 'Jörger-Seifert,', 'Passiv', 'Mitglied', '-', false, 'member', null),
('155', 'Harald', 'Jacobi', 'Passiv', 'Mitglied', '-', false, 'member', null),
('153', 'Friedolin', 'Hüber', 'Aktiv', 'Ehrenmitglied', 'Innewasser Ehrenmitglied + Rheinlos Erwachsener', false, 'member', null),
('152', 'Matthias', 'Hryhoruk', 'Aktiv', 'Mitglied', 'Innenwasser + Rheinlos', false, 'member', null),
('150', 'Rainer', 'Zürcher', 'Aktiv', 'Mitglied', 'Innenwasser + Rheinlos', false, 'member', null),
('147', 'Harald', 'Zipf', 'Aktiv', 'Mitglied', 'Innenwasser + Rheinlos', false, 'member', null),
('144', 'Paul', 'Ziegler', 'Aktiv', 'Mitglied', 'Innenwasser Erwachsener', false, 'member', null),
('142', 'Reinhard', 'Wirth', 'Passiv', 'Mitglied', '-', false, 'member', null),
('141', 'Reinhard', 'Wilhelm', 'Passiv', 'Mitglied', '-', false, 'member', null),
('137', 'Norbert', 'Weide', 'Aktiv', 'Mitglied', 'Innenwasser + Rheinlos', false, 'member', null),
('136', 'Hans', 'Weide', 'Passiv', 'Ehrenmitglied', '-', false, 'member', null),
('135', 'Erik', 'Weide', 'Aktiv', 'Mitglied', 'Innenwasser + Rheinlos', false, 'member', null),
('134', 'Rolf', 'Weber', 'Passiv', 'Mitglied', '-', false, 'member', null),
('128', 'Sven', 'Wahle', 'Passiv', 'Mitglied', '-', false, 'member', null),
('127', 'Siegfried', 'Wahle', 'Passiv', 'Ehrenmitglied', '-', false, 'member', null),
('126', 'Simon', 'Wäldin', 'Aktiv', 'Mitglied', 'Innenwasser + Rheinlos', false, 'member', null),
('122', 'Udo', 'Trunkenbolz', 'Passiv', 'Mitglied', '-', false, 'member', null),
('119', 'Bernd', 'Trunkenbolz', 'Aktiv', 'Mitglied', 'Innenwasser + Rheinlos', false, 'member', null),
('115', 'Georg', 'Szkopiak', 'Passiv', 'Mitglied', '-', false, 'member', null),
('114', 'Harald', 'Synde', 'Passiv', 'Mitglied', '-', false, 'member', null),
('112', 'Helmut', 'Sucher', 'Aktiv', 'Mitglied', 'Innenwasser + Rheinlos', false, 'member', null),
('110', 'Erhard', 'Sucher', 'Aktiv', 'Mitglied', 'Innenwasser + Rheinlos', false, 'member', null),
('109', 'Doris', 'Sucher', 'Aktiv', 'Mitglied', 'Innenwasser + Rheinlos', false, 'member', null),
('104', 'Walter', 'Stolz', 'Passiv', 'Mitglied', '-', false, 'member', null),
('103', 'Volker', 'Stolz', 'Passiv', 'Mitglied', '-', false, 'member', null),
('94', 'Georg', 'Herrenknecht', 'Passiv', 'Mitglied', '-', false, 'member', null),
('93', 'Udo', 'Henseleit', 'Passiv', 'Ehrenmitglied', '-', false, 'member', null),
('90', 'Florian', 'Heitz', 'Passiv', 'Mitglied', '-', false, 'member', null),
('89', 'Kevin', 'Heimburger', 'Passiv', 'Mitglied', '-', false, 'member', null),
('88', 'Günter', 'Heimburger', 'Aktiv', 'Mitglied', 'Rheinlos Erwachsener', false, 'member', null),
('86', 'Carsten', 'Heimburger', 'Aktiv', 'Ehrenmitglied', 'Innenwasser Ehrenmitglied', false, 'member', null),
('85', 'Bernd', 'Heimburger', 'Passiv', 'Mitglied', '-', false, 'member', null),
('83', 'Rolf', 'Heim', 'Aktiv', 'Mitglied', 'Innenwasser + Rheinlos', false, 'member', null),
('82', 'Michael', 'Hegeholz', 'Aktiv', 'Mitglied', 'Innenwasser + Rheinlos', false, 'member', null),
('77', 'Hansjörg', 'Häß', 'Aktiv', 'Ehrenmitglied', 'Innenwasser Ehrenmitglied', false, 'member', null),
('75', 'Thomas', 'Hädicke', 'Aktiv', 'Mitglied', 'Innenwasser + Rheinlos', false, 'member', null),
('74', 'Dieter', 'Gruseck', 'Passiv', 'Mitglied', '-', false, 'member', null),
('71', 'Detlef', 'Gießler', 'Passiv', 'Mitglied', '-', false, 'member', null),
('70', 'Franz-Josef', 'Gieringer', 'Passiv', 'Mitglied', '-', false, 'member', null),
('68', 'Ulrich', 'Gerster', 'Passiv', 'Mitglied', '-', false, 'member', null),
('60', 'Samuel', 'Fürle', 'Passiv', 'Mitglied', '-', false, 'member', null),
('59', 'Michael', 'Frenk', 'Passiv', 'Mitglied', '-', false, 'member', null),
('56', 'Daniel', 'Frenk', 'Passiv', 'Mitglied', '-', false, 'member', null),
('55', 'Hansjörg', 'Förster', 'Aktiv', 'Mitglied', 'Innenwasser + Rheinlos', false, 'member', null),
('53', 'Gerd', 'Fleig', 'Passiv', 'Mitglied', '-', false, 'member', null),
('52', 'Sven', 'Fischer', 'Aktiv', 'Mitglied', 'Innenwasser + Rheinlos', false, 'member', null),
('49', 'Daniel', 'Feindel', 'Passiv', 'Mitglied', '-', false, 'member', null),
('44', 'Klaus', 'Exner', 'Aktiv', 'Ehrenmitglied', 'Innewasser Ehrenmitglied + Rheinlos Erwachsener', false, 'member', null),
('43', 'Walter', 'Erb', 'Passiv', 'Mitglied', '-', false, 'member', null),
('40', 'Jürgen', 'Erb', 'Passiv', 'Mitglied', '-', false, 'member', null),
('39', 'Erwin', 'Erb', 'Passiv', 'Mitglied', '-', false, 'member', null),
('37', 'Michael', 'Erb', 'Aktiv', 'Mitglied', 'Innenwasser + Rheinlos', false, 'member', null),
('31', 'Andreas', 'Delfosse', 'Passiv', 'Mitglied', '-', false, 'member', null),
('29', 'Rolf', 'Bühler', 'Aktiv', 'Vorstand', 'Innenwasser + Rheinlos VSS Btr. Bf', false, 'member', 'Administrator, Mitglied'),
('27', 'Gerd', 'Bühler', 'Aktiv', 'Mitglied', 'Innenwasser + Rheinlos', false, 'member', null),
('25', 'Wilfried', 'Buchholz', 'Aktiv', 'Mitglied', 'Innenwasser + Rheinlos', false, 'member', null),
('22', 'Robert', 'Braun', 'Aktiv', 'Mitglied', 'Innenwasser Erwachsener', false, 'member', null),
('20', 'Kurt', 'Blümle', 'Passiv', 'Mitglied', '-', false, 'member', null),
('19', 'Hansjörg', 'Blümle', 'Passiv', 'Mitglied', '-', false, 'member', null),
('14', 'Uwe', 'Bertsch', 'Aktiv', 'Mitglied', 'Innenwasser + Rheinlos', false, 'member', null),
('10', 'Sascha', 'Baum', 'Passiv', 'Mitglied', '-', false, 'member', null),
('2', 'Patrick', 'Bachmeier', 'Passiv', 'Mitglied', '-', false, 'member', null)
on conflict (member_no) do update
set first_name = excluded.first_name,
    last_name = excluded.last_name,
    status = excluded.status,
    membership_kind = excluded.membership_kind,
    fishing_card_type = excluded.fishing_card_type,
    is_youth = excluded.is_youth,
    role = excluded.role,
    wiso_roles = excluded.wiso_roles,
    updated_at = now();

-- Sync existing app profiles by member_no (only where account already exists).
alter table if exists public.profiles
  add column if not exists first_name text,
  add column if not exists last_name text,
  add column if not exists membership_kind text,
  add column if not exists fishing_card_type text,
  add column if not exists is_youth boolean not null default false;

update public.profiles p
set first_name = cm.first_name,
    last_name = cm.last_name,
    display_name = trim(concat_ws(' ', cm.first_name, cm.last_name)),
    membership_kind = cm.membership_kind,
    fishing_card_type = cm.fishing_card_type,
    is_youth = cm.is_youth,
    updated_at = now()
from public.club_members cm
where p.member_no = cm.member_no;

commit;
