#!/usr/bin/env bash
set -euo pipefail

SOURCE_FILE=""
DO_GITHUB=false
DO_VERCEL=false
DO_SUPABASE=false
DRY_RUN=false

usage() {
  cat <<'USAGE'
Usage:
  bash scripts/secrets-apply.sh --source <file> [--github] [--vercel] [--supabase] [--dry-run]

Requirements by target:
  --github   needs GH_REPO and TARGET_ENV
  --vercel   needs TARGET_ENV and linked vercel project
  --supabase needs SUPABASE_PROJECT_REF

The source file should contain export statements generated by secrets-generate.sh
plus your existing env values for Supabase/Vercel/GitHub where needed.
USAGE
}

require_cmd() {
  if ! command -v "$1" >/dev/null 2>&1; then
    echo "ERROR: missing command: $1"
    exit 1
  fi
}

while [ "$#" -gt 0 ]; do
  case "$1" in
    --source)
      SOURCE_FILE="${2:-}"
      shift 2
      ;;
    --github)
      DO_GITHUB=true
      shift
      ;;
    --vercel)
      DO_VERCEL=true
      shift
      ;;
    --supabase)
      DO_SUPABASE=true
      shift
      ;;
    --dry-run)
      DRY_RUN=true
      shift
      ;;
    --help|-h)
      usage
      exit 0
      ;;
    *)
      echo "Unknown option: $1"
      usage
      exit 1
      ;;
  esac
done

if [ -z "$SOURCE_FILE" ]; then
  echo "ERROR: --source is required"
  usage
  exit 1
fi

if [ "$DO_GITHUB" = false ] && [ "$DO_VERCEL" = false ] && [ "$DO_SUPABASE" = false ]; then
  echo "ERROR: choose at least one target (--github|--vercel|--supabase)"
  exit 1
fi

if [ ! -f "$SOURCE_FILE" ]; then
  echo "ERROR: source file not found: $SOURCE_FILE"
  exit 1
fi

set -a
# shellcheck disable=SC1090
source "$SOURCE_FILE"
set +a

: "${TARGET_ENV:=staging}"

set_secret_gh() {
  local key="$1"
  local value="${!1:-}"
  if [ -z "$value" ]; then
    echo "SKIP github: $key (not set in source)"
    return 0
  fi
  if [ "$DRY_RUN" = true ]; then
    echo "DRY github set $key"
  else
    gh secret set "$key" --repo "$GH_REPO" --env "$TARGET_ENV" --body "$value"
    echo "OK github set $key"
  fi
}

set_env_vercel() {
  local key="$1"
  local value="${!1:-}"
  local target="$2"
  if [ -z "$value" ]; then
    echo "SKIP vercel: $key (not set in source)"
    return 0
  fi
  if [ "$DRY_RUN" = true ]; then
    echo "DRY vercel set $key ($target)"
  else
    printf '%s\n' "$value" | vercel env add "$key" "$target" >/dev/null
    echo "OK vercel add $key ($target)"
  fi
}

if [ "$DO_GITHUB" = true ]; then
  require_cmd gh
  : "${GH_REPO:?GH_REPO required for --github}"

  gh_keys=(
    VERCEL_TOKEN
    VERCEL_ORG_ID
    VERCEL_PROJECT_ID
    VERCEL_STAGING_DOMAIN
    VERCEL_BETA_DOMAIN
    PUBLIC_SUPABASE_URL
    PUBLIC_SUPABASE_ANON_KEY
    PUBLIC_SUPABASE_PUBLISHABLE_KEY
    PUBLIC_VAPID_PUBLIC_KEY
    PUBLIC_MEMBER_CARD_VERIFY_PUBKEY
    PUBLIC_APP_NAME
    PUBLIC_APP_BRAND
    PUBLIC_APP_CHANNEL
    PUBLIC_APP_VERSION
    PUBLIC_ENABLE_PASSWORD_RESET
    PUBLIC_TURNSTILE_SITE_KEY
    SUPABASE_URL
    SUPABASE_SERVICE_ROLE_KEY
    PUSH_NOTIFY_TOKEN
  )

  for k in "${gh_keys[@]}"; do
    set_secret_gh "$k"
  done
fi

if [ "$DO_VERCEL" = true ]; then
  require_cmd vercel
  vercel_target="preview"
  if [ "$TARGET_ENV" = "prod" ]; then
    vercel_target="production"
  fi

  vercel_keys=(
    PUBLIC_SUPABASE_URL
    PUBLIC_SUPABASE_ANON_KEY
    PUBLIC_SUPABASE_PUBLISHABLE_KEY
    PUBLIC_VAPID_PUBLIC_KEY
    PUBLIC_MEMBER_CARD_VERIFY_PUBKEY
    PUBLIC_APP_NAME
    PUBLIC_APP_BRAND
    PUBLIC_APP_CHANNEL
    PUBLIC_APP_VERSION
    PUBLIC_ENABLE_PASSWORD_RESET
    PUBLIC_TURNSTILE_SITE_KEY
    SUPABASE_URL
    SUPABASE_SERVICE_ROLE_KEY
    PUSH_NOTIFY_TOKEN
  )

  for k in "${vercel_keys[@]}"; do
    set_env_vercel "$k" "$vercel_target"
  done
fi

if [ "$DO_SUPABASE" = true ]; then
  require_cmd supabase
  : "${SUPABASE_PROJECT_REF:?SUPABASE_PROJECT_REF required for --supabase}"

  : "${SUPABASE_URL:?SUPABASE_URL missing}"
  : "${SUPABASE_SERVICE_ROLE_KEY:?SUPABASE_SERVICE_ROLE_KEY missing}"
  : "${PUSH_NOTIFY_TOKEN:?PUSH_NOTIFY_TOKEN missing}"
  : "${VAPID_PRIVATE_KEY:?VAPID_PRIVATE_KEY missing}"
  : "${VAPID_SUBJECT:?VAPID_SUBJECT missing}"

  vapid_public="${PUBLIC_VAPID_PUBLIC_KEY:-${VAPID_PUBLIC_KEY:-}}"
  : "${vapid_public:?PUBLIC_VAPID_PUBLIC_KEY (or VAPID_PUBLIC_KEY) missing}"

  if [ "$DRY_RUN" = true ]; then
    echo "DRY supabase secrets set for project $SUPABASE_PROJECT_REF"
  else
    supabase secrets set \
      SUPABASE_URL="$SUPABASE_URL" \
      SUPABASE_SERVICE_ROLE_KEY="$SUPABASE_SERVICE_ROLE_KEY" \
      PUSH_NOTIFY_TOKEN="$PUSH_NOTIFY_TOKEN" \
      VAPID_PUBLIC_KEY="$vapid_public" \
      VAPID_PRIVATE_KEY="$VAPID_PRIVATE_KEY" \
      VAPID_SUBJECT="$VAPID_SUBJECT" \
      --project-ref "$SUPABASE_PROJECT_REF"
    echo "OK supabase secrets updated for $SUPABASE_PROJECT_REF"
  fi
fi

echo "Done."
